version: '3.7'

services:

  server:
    build:
      context: ./server
      dockerfile: .Dockerfile
    container_name: dormakaba_server
    volumes:
      - ./server:/usr/app
    ports:
      - 5000:5000
    environment:
      - MONGO_URL=mongodb+srv://dormakaba:dormakaba@cluster0.1yiwk.mongodb.net
      - CLIENT=http://localhost:3000
    networks:
      - mern-network

  client:
    build:
      context: ./client
      dockerfile: .Dockerfile
    container_name: dormakaba_client
    volumes:
      - ./client/:/usr/app
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      - API_SERVER=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge